nouns = nouns.concat([
    'Mumble',
    'Skipper',
    'Kowalski',
    'Rico',
    'Private',
    'Helen the Penguin',
    'Chilly Willy',
    'Pingu',
    'Ramón',
    'Lovelace',
    'Mr. Popper',
    'Captain Cook',
    'Presley',
    'Wheezy',
    'Tacky',
    'Opus',
    'Pablo',
    'Feathers McGraw',
    'Gunter',
    'Peng',
    'Cody Maverick',
    'Tip',
    'Hubi',
    'Marina',
    'Rocko',
    'Fred',
    'Penny',
    'Marlon',
    'Topper',
    'Peso',
    'Tootsie the Penguin',
    'Tuxedo Sam',
    'Peggi',
    'Emperor',
    'King',
    'Adelie',
    'Rockie',
    'Macaroni',
    'Chinstrap',
    'Gentoo',
    'Little Blue',
    'Magellan',
    'Humboldt',
]);